//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Portable.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class EmployeeLeave : BaseEntity
    {
        
        public virtual int EmployeeLeaveId { get; set; }              
        public int LeaveDaysRequest { get; set; }
        public virtual string Reason { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int LeaveYear { get; set; }
        public virtual string UserId { get; set; }
        public int LeaveTypeId { get; set; }
    
     
    }
}
