//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Portable.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class LeaveType : BaseEntity
    {
        public virtual int LeaveTypeId { get; set; }
        public virtual string Name { get; set; }
        public int LeaveDaysAllowed { get; set; }
        public int LeaveYear { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int LeaveInstance { get; set; }
  
       
    }
}
